name: Build multi-arch image on AWS spot instances

on: workflow_dispatch

concurrency:
  cancel-in-progress: false
  group: run-on-spot

jobs:
  spawn-spots:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_docker_login: ${{ secrets.DOCKERHUB_USERNAME }}
      TF_VAR_docker_password: ${{ secrets.DOCKERHUB_TOKEN }}
      TF_VAR_docker_image: ${{ secrets.DOCKERHUB_IMAGE }}
      TF_VAR_repository_url: ${{ github.repositoryUrl }}
      TF_VAR_checkout: ${{ github.sha }}
    outputs:
      PUBLIC_IPS: ${{ env.PUBLIC_IPS }}
      PRIVATE_KEY: ${{ env.PRIVATE_KEY }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
      -
        name: "Terraform: Setup"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5
          terraform_wrapper: false
      -
        name: "Terraform: Init"
        run: terraform -chdir=terraform init
      -
        name: "Terraform: Apply"
        run: terraform -chdir=terraform apply -auto-approve
      -
        name: "Save Terraform State File"
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: terraform-state
          path: terraform/terraform.tfstate
          retention-days: 1
      -
        id: outputs
        name: "Terraform: Parse Outputs"
        run: |
          PRIVATE_KEY=$(terraform -chdir=terraform output private_key)
          PUBLIC_IPS=$(terraform -chdir=terraform output --json public_ips)

          echo "PRIVATE_KEY<<EOF" >> $GITHUB_ENV
          echo "$PRIVATE_KEY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          echo "PUBLIC_IPS<<EOF" >> $GITHUB_ENV
          echo "$PUBLIC_IPS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

  build:
    runs-on: ubuntu-latest
    needs:
      - spawn-spots
    strategy:
      matrix:
        PUBLIC_IP: ${{ fromJSON(needs.spawn-spots.outputs.PUBLIC_IPS) }}
    env:
      PUBLIC_IP: ${{ matrix.PUBLIC_IP }}
    steps:
      -
        name: Setup SSH client
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          cat >>~/.ssh/config <<END
          Host spot
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/private.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ubuntu
          SSH_HOST: ${{ env.PUBLIC_IP }}
          PRIVATE_KEY: ${{ needs.spawn-spots.outputs.PRIVATE_KEY }}
      -
        name: Execute remote SSH command
        run: ssh spot 'uname -a'

  destroy-spots:
    runs-on: ubuntu-latest
    needs:
      - spawn-spots
      - build
    if: ${{ always() }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_docker_login: ${{ secrets.DOCKERHUB_USERNAME }}
      TF_VAR_docker_password: ${{ secrets.DOCKERHUB_TOKEN }}
      TF_VAR_docker_image: ${{ secrets.DOCKERHUB_IMAGE }}
      TF_VAR_repository_url: ${{ github.repositoryUrl }}
      TF_VAR_checkout: ${{ github.sha }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
      -
        name: "Download Terraform State File"
        uses: actions/download-artifact@v2
        with:
          name: terraform-state
          path: terraform
      -
        name: "Terraform: Setup"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5
          terraform_wrapper: false
      -
        name: "Terraform: Init"
        run: terraform -chdir=terraform init
      -
        name: "Terraform: Destroy"
        run: terraform -chdir=terraform destroy -auto-approve
